FROM python:3.11-slim

WORKDIR /app

# Install dependencies needed
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source code
COPY api /app/api
COPY common /app/common
COPY worker /app/worker

# Set python path so modules work correctly
ENV PYTHONPATH="/app"
