steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.api',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/tcdd-api:latest',
        '.'
      ]
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/tcdd-api:latest'
