steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'BASE_IMAGE=${_BASE_IMAGE}',
        '-f',
        'Dockerfile.worker',
        '-t',
        '${_WORKER_IMAGE}',
        '.'
      ]
images:
  - '${_WORKER_IMAGE}'
